###
curl -i -X POST -H "Content-Type: application/json" http://localhost:8883/registration -d '{"name": "Ravi"}'
###
curl http://localhost:8883/users/3

###
curl http://localhost:8883/accounts?ownerId=3

###
curl -i -X POST -H "Content-Type: application/json" http://localhost:8883/projects -d '{"name": "Basket Weaving", "accountId": 3}'
###
curl -i localhost:8883/projects?accountId=<ACCOUNT-ID>